config/routes.rb
Pollster::Application.routes.draw do
  root to: "polls#index"

  match '/polls/:id/edit/:edit_hash' => "polls#edit"

  resources :polls do
    resources :questions
  end

  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :poll_id
  belongs_to :question
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name, :vanity_url
  before_save :generate_edit_code
  
  has_many :questions
  
  private
  
  def generate_edit_code
    self.edit_url = (0...8).map{65.+(rand(26)).chr}.join
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description
  belongs_to :poll
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])

    @answer.save
    
    respond_to { |format| format.js }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def new
    @poll = Poll.new
  end
  
  def create
    @poll = Poll.new(params[:poll])
    
    if @poll.save
      redirect_to @poll, :notice => "New poll created successfully!"
    else
      render new_poll
    end
  end

  def show
    if params[:id].to_i > 0
      @poll = Poll.find(params[:id])
    else
      show_vanity_url      
    end
  end
  
  def show_vanity_url
    @poll = Poll.find_by_vanity_url(params[:id])
  end

  def index
    @polls = Poll.all
  end

  def edit
    @poll = Poll.find(params[:id])
  end
  
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy
        
    redirect_to root_path
  end
  
  def update
    @poll = Poll.find(params[:id])
    if @poll.update_attributes(params[:poll])
      redirect_to @poll
    else
      render :edit
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    @poll = Poll.find(params[:poll_id])
    @question = @poll.questions.build(params[:question])
    @question.save
    @questions = @poll.questions
    
    respond_to { |format| format.js }
  end

  def edit
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    
    redirect_to Poll.find(params[:poll_id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    
    respond_to { |format| format.js }
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/answers/_form.html.erb
<%= div_for question do %>
	<p>
		<%= question.description %>
	</p>
	<p>
		<%= form_for [question, @answer = Answer.new], :remote => true, :html => { :class => 'form-horizontal' } do |f| %>
		  <div class="control-group">
		    <div class="controls">
		      <%= f.text_field :body, :class => 'text_field' %>
		    </div>
		  </div>
		  <br>
		  <div class="form-actions">
		    <%= f.submit "Submit answer", :class => 'btn btn-primary' %>
		  </div>
		<% end %>
	</p>
<% end %>

app/views/answers/create.js.erb
$question = $('#<%= dom_id(@question) %>')
$question.children().not('p').fadeOut(50);
if ($question.get(0) === $('.question').last().get(0)){
	window.location.href = ("http://qkme.me/3rsaxi");
}
// $('#<%= dom_id(@question) %>').replaceWith("Answer submitted!");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :vanity_url, "Custom poll url", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vanity_url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/_poll_maker_nav.erb
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/polls/edit.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :vanity_url, "Custom poll url", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vanity_url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Update", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.id, poll_path(poll) %></td>
        <td><%= link_to "#{poll.name}", poll_path(poll) %></td>
        <td><%=l poll.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_poll_path(poll), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_path(poll),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/public_poll.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poll.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<hr>

<% @poll.questions.each do |question| %>
<p><%= question.description %></p>
<% end %>

app/views/polls/show.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => @poll.name %>
	<% if params[:id].to_i > 0 %>  |
	    <%= link_to "Public view", @poll.vanity_url %>
	<% end %>
  </h1>
</div>

<% if params[:id].to_i > 0 %>
<div class="questions">	
	<%= render 'poll_maker_nav'%>
	
	<%= render :partial => 'questions/poll_maker_question', :collection => @poll.questions, :as => :question || 'No questions have been added yet!' %>
</div>
	<%= render 'questions/form' %>

<% else %>

	<%= render :partial => 'answers/form', :collection => @poll.questions, :as => :question || 'No questions have been added yet!' %>
	
<% end %>

app/views/questions/_form.html.erb
<%= form_for [@poll, @question = Question.new], :remote => true, :method => :create, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, "Add Question:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <br>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_poll_maker_question.html.erb
<%= div_for question do %>
	<%= question.description %> | 
	<%= link_to "Edit", edit_poll_question_path(@poll, question) %> |
	<%= link_to "Delete", poll_question_path(@poll, question), method: :delete, :remote => true %>
	<table class="table table-condensed table-striped table-bordered">
		<thead>
			<tr>
				<th>Submission Time</th>
				<th>Answer</th>
			</tr>
		</thead>
		<% question.answers.each do |answer| %>
		<tr>
			<th><%= answer.created_at %></th>
			<th><%= answer.body %></th>
		</tr>
		<% end %>
	</table>
<% end %>

app/views/questions/create.js.erb
$(".questions").fadeIn(50);
$(".questions").append("<%= j render 'questions/poll_maker_question', :question => @question %>");

app/views/questions/delete.html.erb
<h1>Question#delete</h1>
<p>Find me in app/views/question/delete.html.erb</p>

app/views/questions/destroy.js.erb
$('#<%= dom_id(@question) %>').fadeOut(50);

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= form_for [@poll, @question], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, "Edit Question:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <br>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>